packer {
  required_plugins {
    hcloud = {
      source  = "github.com/hetznercloud/hcloud"
      version = ">= 1.3.0"
    }
  }
}

locals {
  timestamp = formatdate("YYYYMMDD-hhmmss", timestamp())
  snapshot_name = "${var.snapshot_name}-${local.timestamp}"
}

source "hcloud" "wireguard" {
  image        = var.base_image
  location     = var.location
  server_type  = var.server_type
  server_name  = "packer-wireguard-builder"
  ssh_username = "root"

  snapshot_name = local.snapshot_name
  snapshot_labels = {
    "app"                       = "wireguard"
    "build_timestamp"           = local.timestamp
    "wireguard_ui_version"      = var.wireguard_ui_version
    "secret_operator_version"  = var.secret_operator_version
    "packer_build"              = "true"
  }
}

build {
  sources = ["source.hcloud.wireguard"]

  # Build verify binary for target OS/architecture
  provisioner "shell-local" {
    inline = [
      "echo 'Building wireguard-verify binary for ${var.target_goos}/${var.target_goarch}...'",
      "OUTDIR=\"$(cd ${path.root} && pwd)\" && cd \"$OUTDIR/../../../\" && GOOS=${var.target_goos} GOARCH=${var.target_goarch} go build -o \"$OUTDIR/wireguard-verify\" ./cmd/verify/"
    ]
  }

  # Generate versions.env file from template
  provisioner "file" {
    content = templatefile("${path.root}/scripts/versions.env.tpl", {
      wireguard_ui_version     = var.wireguard_ui_version
      secret_operator_version  = var.secret_operator_version
    })
    destination = "/tmp/versions.env"
  }

  # Upload all provisioner scripts (product-specific + shared)
  provisioner "file" {
    source      = "${path.root}/scripts/"
    destination = "/tmp/"
  }

  # Upload shared scripts (nginx, security, cleanup) from the common directory
  provisioner "file" {
    source      = "${path.root}/../shared/scripts/"
    destination = "/tmp/"
  }

  # Upload verify binary to permanent location (generated by shell-local provisioner above)
  provisioner "file" {
    source      = "${path.root}/wireguard-verify"
    destination = "/usr/local/bin/wireguard-verify"
    generated   = true
  }

  # Make scripts executable and run them in order
  provisioner "shell" {
    inline = [
      "chmod +x /tmp/*.sh /usr/local/bin/wireguard-verify",
      ". /tmp/versions.env && /tmp/01-base-packages.sh",
      ". /tmp/versions.env && /tmp/02-wireguard-binaries.sh",
      "WIREGUARD_DOMAIN=${var.wireguard_domain} SECRET_OPERATOR_TOKEN=${var.secret_operator_token} /tmp/03-fetch-secrets.sh",
      "/tmp/nginx-setup.sh",
      "/tmp/04-systemd-services.sh",
      "/tmp/security-hardening.sh",
      "/usr/local/bin/wireguard-verify --local --prebaked --target wireguard",
      "/tmp/cleanup.sh"
    ]
    environment_vars = [
      "DEBIAN_FRONTEND=noninteractive"
    ]
  }

  # Clean up local verify binary
  provisioner "shell-local" {
    inline = [
      "rm -f ${path.root}/wireguard-verify"
    ]
  }

  post-processor "manifest" {
    output     = "manifest.json"
    strip_path = true
    custom_data = {
      snapshot_name            = local.snapshot_name
      wireguard_ui_version     = var.wireguard_ui_version
      secret_operator_version  = var.secret_operator_version
    }
  }
}