providers:
  gsm:
    kind: google_secretmanager
    maps:
      - id: gke
        path: projects/gke-1-368016
        keys:
          FRANKY_OLLAMA_KEY: OLLAMA_API_KEY
          FRANKY_GEMINI_API_KEY: GEMINI_API_KEY
          FRANKY_CLOUDFLARE_API_KEY: CF_API_TOKEN
          FRANKY_CF_ACCOUNT_ID: CF_ACCOUNT_ID
          FRANKY_OPENROUTER_API_KEY: OPENROUTER_KEY
          FRANKY_MISTRAL_API_KEY: MISTRAL_API_KEY
          FRANKY_OPENAI_API_KEY: OPENAI_API_KEY
          # FRANKY_CEREBRAS_API_KEY: CEREBRAS_API_KEY