#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: true

manage-resolv-conf: true
resolv_conf:
  nameservers:
    - "8.8.8.8"
    - "8.8.4.4"

packages:
  - curl
  - git
  - jetty9

# Todo not enough disk space yet
# swap:
#   filename: /swap.img
#   size: "auto" # or size in bytes
#   maxsize: 8G
write_files:
  - path: /etc/default/jetty9
    permissions: 0644
    owner: root
    content: |
      # change to 'no' or uncomment to use the default setting in /etc/default/rcS 
      VERBOSE=yes

      # Run Jetty as this user ID (default: jetty)
      # Set this to an empty string to prevent Jetty from starting automatically
      #JETTY_USER=jetty

      # The home directory of the Java Runtime Environment (JRE). You need at least
      # Java 8. If JAVA_HOME is not set, some common directories for OpenJDK and
      # the Oracle JDK are tried.
      #JAVA_HOME=

      # Extra options to pass to the JVM
      #JAVA_OPTIONS="-Djava.awt.headless=true"

      # Timeout in seconds for the shutdown of all webapps
      #JETTY_SHUTDOWN=30

      # Additional arguments to pass to Jetty
      #JETTY_ARGS=

      # Jetty uses a directory to store temporary files like unpacked webapps
      #JETTY_TMP=/var/cache/jetty9

      # Default for number of days to keep old log files in /var/log/jetty9/
      #LOGFILE_DAYS=14

      # If you run Jetty on port numbers that are all higher than 1023, then you
      # do not need authbind. It is used for binding Jetty to lower port numbers.
      # (yes/no, default: no)
      AUTHBIND=yes
  - path: /etc/jetty9/start.d/eucaptcha.ini
    permissions: 0644
    owner: root
    content: |
      jetty.port=80

runcmd:
  - cd /tmp
  - git clone https://github.com/fr123k/EU-CAPTCHA.git
  - cp /tmp/EU-CAPTCHA/clientfiles/EuCaptcha.war /usr/share/jetty9/webapps
  - systemctl start jetty9.service
  - systemctl enable jetty9.service
