#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: false

manage-resolv-conf: true
resolv_conf:
  nameservers:
    - "8.8.8.8"
    - "8.8.4.4"

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - git

# Todo not enough disk space yet
# swap:
#   filename: /swap.img
#   size: "auto" # or size in bytes
#   maxsize: 8G

write_files:
  - path: /etc/systemd/system/jocker.service.env
    permissions: 0644
    owner: root
    content: |
      SEED_JOB_GIT_REPO=fr123k/jocker
      SEED_JOB_GROOVY_FILE=shared-library/pipeline-jobs.groovy
      JENKINS_MASTER=http://172.17.0.1:80
      JOBS_LIST=eyJqb2JzIjogW3sgInJlcG9zaXRvcnkiOiJodHRwczovL2dpdGh1Yi5jb20vZnIxMjNrL2plbmtpbnMtam9icyIsICJqb2JEU0xSZXZpc2lvbiI6ICJtYWluIiwgImpvYkRTTFBhdGgiOiJqZW5raW5zL2F3cy9qb2JEU0wiLCAicmVtb3ZlZEpvYkFjdGlvbiI6IklHTk9SRSIgfV19
      SEED_BRANCH_JOBS=origin/master
      {{ AWS_KEY_ID }}
      {{ AWS_KEY_SECRET }}
      {{ ADMIN_PASSWORD }}

  - path: /etc/systemd/system/jocker.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Run an jocker container
      Author=Frank Ittermann
      Requires=docker.service
      After=docker.service

      [Service]
      TimeoutStartSec=0
      Restart=always
      ExecStartPre=-/usr/bin/docker rm -f jocker
      ExecStart=-/usr/bin/docker run --rm --memory 2g -p 50000:50000 -p 80:8080 --env-file /etc/systemd/system/jocker.service.env --name jocker fr123k/jocker
      ExecStop=/usr/bin/docker stop -t 2 jocker

      [Install]
      WantedBy=multi-user.target

  - path: /etc/systemd/system/jocker-agent-pre.sh
    permissions: 0755
    owner: root
    content: |
      #!/bin/bash

      echo "Admin pass ${ADMIN_PASSWORD}"
      echo -n "AGENT_SECRET=" > /etc/systemd/system/jocker-agent.service.secret.env
      curl -L -s http://admin:${ADMIN_PASSWORD}@localhost:80/computer/docker-1/slave-agent.jnlp | sed "s/.*<application-desc main-class=\"hudson.remoting.jnlp.Main\"><argument>\([a-z0-9]*\).*/\1/" >> /etc/systemd/system/jocker-agent.service.secret.env

      mkdir -p /home/agent
      curl -o /home/agent/agent.jar http://admin:${ADMIN_PASSWORD}@localhost:80/jnlpJars/agent.jar

  - path: /etc/systemd/system/jocker-agent.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Run an jocker container
      Requires=jocker.service
      After=jocker.service
      StartLimitInterval=30
      StartLimitBurst=5

      [Service]
      Restart=always
      TimeoutStartSec=0
      Restart=always
      RestartSec=30

      EnvironmentFile=/etc/systemd/system/jocker.service.env
      EnvironmentFile=-/etc/systemd/system/jocker-agent.service.secret.env
      ExecStartPre=-/etc/systemd/system/jocker-agent-pre.sh ${ADMIN_PASSWORD}
      ExecStart=-/usr/bin/java -jar /home/agent/agent.jar -jnlpUrl http://172.17.0.1:80/computer/docker-1/slave-agent.jnlp -noReconnect -secret ${AGENT_SECRET} -workDir "/home/agent/"

      [Install]
      WantedBy=multi-user.target

runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io openjdk-8-jre-headless
  - systemctl start docker
  - systemctl enable docker
  - systemctl daemon-reload
  - docker pull fr123k/jocker
  - docker pull fr123k/jocker-agents-pulumi
  - systemctl start jocker.service
  - systemctl enable jocker.service
  - systemctl start jocker-agent.service
  - systemctl enable jocker-agent.service
