#!/bin/bash
# Auto-generated version file - DO NOT EDIT
# This file is generated by Packer during the build process

export TEMPORAL_CLI_VERSION="${temporal_cli_version}"
export TEMPORAL_SERVER_VERSION="${temporal_server_version}"
export TEMPORAL_UI_VERSION="${temporal_ui_version}"
export TEMPORAL_WORKER_VERSION="${temporal_worker_version}"
export SECRET_OPERATOR_VERSION="${secret_operator_version}"
export OAUTH2_STORAGE_VERSION="${oauth2_storage_version}"
export DUNEBOT_VERSION="${dunebot_version}"
