#!/bin/bash
# Auto-generated version file - DO NOT EDIT
# This file is generated by Packer during the build process

export WIREGUARD_UI_VERSION="${wireguard_ui_version}"
export SECRET_OPERATOR_VERSION="${secret_operator_version}"
export TARGET_GOARCH="${target_goarch}"