packer {
  required_plugins {
    virtualbox = {
      source  = "github.com/hashicorp/virtualbox"
      version = "~> 1"
    }
  }
}

locals {
  timestamp     = formatdate("YYYYMMDD-hhmmss", timestamp())
  artifact_name = "${var.vm_name}-${local.timestamp}"
}

source "virtualbox-ovf" "cloudinit_test" {
  source_path      = "${var.source_path}"
  output_directory = var.output_directory
  vm_name          = local.artifact_name
  format           = "ova"
  headless         = true

  ssh_username         = var.ssh_username
  ssh_password         = var.ssh_password
  ssh_private_key_file = var.ssh_private_key_file
  ssh_timeout          = "20m"

  shutdown_command  = "sudo -S shutdown -P now"
  shutdown_timeout  = "5m"

  vboxmanage = [
    ["modifyvm", "{{.Name}}", "--nat-localhostreachable1", "on"],
    ["modifyvm", "{{.Name}}", "--memory", var.memory],
    ["modifyvm", "{{.Name}}", "--cpus", var.cpus]
  ]
}

build {
  sources = ["source.virtualbox-ovf.cloudinit_test"]

  # ────────────────────────────────────────────────
  # Step 0: Build the verify binary for the guest arch
  # (mirrors the packer/hetzner/{wireguard,temporal} flows)
  # ────────────────────────────────────────────────
  provisioner "shell-local" {
    inline = [
      "echo 'Building verify binary for ${var.target_goos}/${var.target_goarch}...'",
      "OUTDIR=\"$(cd ${path.root} && pwd)\" && cd \"$OUTDIR/../../\" && GOOS=${var.target_goos} GOARCH=${var.target_goarch} go build -o \"$OUTDIR/verify\" ./cmd/verify/"
    ]
  }

  # ────────────────────────────────────────────────
  # Step 1: Upload scripts + verify binary
  # ────────────────────────────────────────────────
  provisioner "file" {
    source      = "${path.root}/scripts/render.sh"
    destination = "/tmp/render.sh"
  }

  provisioner "file" {
    source      = "${path.root}/../../${var.cloud_init_file}"
    destination = "/tmp/cloud-init-template.txt"
  }

  # Upload the pre-built verify binary (generated by shell-local above).
  # The cloud-init script installs it to /usr/local/bin/verify and runs it.
  provisioner "file" {
    source      = "${path.root}/verify"
    destination = "/tmp/verify"
    generated   = true
  }

  # ────────────────────────────────────────────────
  # Step 2: Render cloud-init and execute it
  # ────────────────────────────────────────────────
  provisioner "shell" {
    only   = ["virtualbox-ovf.cloudinit_test"]
    execute_command = "sudo -S -E env {{ .Vars }} bash -e -o pipefail '{{.Path}}'"
    inline = [
      "chmod +x /tmp/*.sh",
      "sudo cp /home/packer/.ssh/authorized_keys /root/.ssh/authorized_keys",
      "/tmp/render.sh /tmp/cloud-init-template.txt /tmp/cloud-init.sh",
      "/tmp/cloud-init.sh",
    ]
    environment_vars = [
      "DEBIAN_FRONTEND=noninteractive",
      "DOMAIN=${var.domain}",
      "TEMPORAL_DOMAIN=${var.temporal_domain}",
      "DUNEBOT_DOMAIN=${var.dunebot_domain}",
      "CLIENT_PUBLICKEY=${var.client_publickey}",
      "CLIENT_IP_ADDRESS=${var.client_ip_address}",
      "SECRET_OPERATOR_TOKEN=${var.secret_operator_token}",
    ]
  }

  post-processor "manifest" {
    output     = "${path.root}/manifest.json"
    strip_path = true
    custom_data = {
      artifact_name   = local.artifact_name
      source_path     = var.source_path
      cloud_init_file = var.cloud_init_file
      target          = var.target
      mode            = var.mode
    }
  }
}