packer {
  required_plugins {
    hcloud = {
      source  = "github.com/hetznercloud/hcloud"
      version = ">= 1.3.0"
    }
  }
}

locals {
  timestamp = formatdate("YYYYMMDD-hhmmss", timestamp())
  snapshot_name = "${var.snapshot_name}-${local.timestamp}"
  artifact_name = "${var.vm_name}-${local.timestamp}"
}

source "hcloud" "temporal" {
  image        = var.base_image
  location     = var.location
  server_type  = var.server_type
  server_name  = "packer-temporal-builder"
  ssh_username = "root"

  snapshot_name = local.snapshot_name
  snapshot_labels = {
    "app"                      = "temporal"
    "build_timestamp"          = local.timestamp
    "temporal_cli_version"     = var.temporal_cli_version
    "temporal_server_version"  = var.temporal_server_version
    "temporal_ui_version"      = var.temporal_ui_version
    "temporal_worker_version"  = var.temporal_worker_version
    "secret_operator_version"  = var.secret_operator_version
    "oauth2_storage_version"   = var.oauth2_storage_version
    "dunebot_version"          = var.dunebot_version
    "packer_build"             = "true"
  }
}

# ────────────────────────────────────────────────
# VirtualBox source (local testing against packer_base image)
# Selected via: packer build -only=virtualbox-ovf.wireguard .
# Outputs an OVA file.
# ────────────────────────────────────────────────
source "virtualbox-ovf" "temporal" {
  source_path          = var.source_path
  vm_name              = local.artifact_name
  output_directory     = var.output_directory
  format               = "ova"
  headless             = true

  ssh_username         = var.ssh_username
  ssh_password         = var.ssh_password
  ssh_private_key_file = var.ssh_private_key_file
  ssh_timeout          = "20m"

  # Graceful shutdown via sudo (passwordless sudo configured in the base image).
  shutdown_command     = "sudo -S shutdown -P now"
  shutdown_timeout     = "5m"

  vboxmanage = [
    ["modifyvm", "{{.Name}}", "--nat-localhostreachable1", "on"],
    ["modifyvm", "{{.Name}}", "--memory", var.memory],
    ["modifyvm", "{{.Name}}", "--cpus", var.cpus]
  ]
}

build {
  sources = [
    "source.hcloud.temporal",
    "source.virtualbox-ovf.temporal"
  ]

  # Build verify binary for target OS/architecture
  provisioner "shell-local" {
    inline = [
      "echo 'Building verify binary for ${var.target_goos}/${var.target_goarch}...'",
      "OUTDIR=\"$(cd ${path.root} && pwd)\" && cd \"$OUTDIR/../../../\" && GOOS=${var.target_goos} GOARCH=${var.target_goarch} go build -o \"$OUTDIR/verify\" ./cmd/verify/"
    ]
  }

  # Generate versions.env file from template
  provisioner "file" {
    content = templatefile("${path.root}/scripts/versions.env.tpl", {
      temporal_cli_version     = var.temporal_cli_version
      temporal_server_version  = var.temporal_server_version
      temporal_ui_version      = var.temporal_ui_version
      temporal_worker_version  = var.temporal_worker_version
      secret_operator_version  = var.secret_operator_version
      oauth2_storage_version   = var.oauth2_storage_version
      dunebot_version          = var.dunebot_version
      target_goarch            = var.target_goarch
    })
    destination = "/tmp/versions.env"
  }

  # Upload all provisioner scripts (product-specific + shared)
  provisioner "file" {
    source      = "${path.root}/scripts/"
    destination = "/tmp/"
  }

  # Upload shared scripts (nginx, security, cleanup) from the common directory
  provisioner "file" {
    source      = "${path.root}/../../shared/scripts/"
    destination = "/tmp/"
  }

  # Upload verify binary to permanent location (generated by shell-local provisioner above)
  provisioner "file" {
    source      = "${path.root}/verify"
    destination = "/tmp/verify"
    generated   = true
  }

  # Make scripts executable and run them in order
  provisioner "shell" {
    execute_command = "sudo -S -E env {{ .Vars }} sh '{{ .Path }}'"
    inline = [
      "mv /tmp/verify /usr/local/bin/",
      "chmod +x /tmp/*.sh /usr/local/bin/verify",
      ". /tmp/versions.env && /tmp/01-base-packages.sh",
      ". /tmp/versions.env && /tmp/02-temporal-binaries.sh",
      ". /tmp/versions.env && /tmp/03-dunebot-binaries.sh",
      ". /tmp/versions.env && /tmp/nginx-setup.sh",
      ". /tmp/versions.env && /tmp/05-systemd-services.sh",
      ". /tmp/versions.env && /tmp/security-hardening.sh",
      "/usr/local/bin/verify --local --prebaked --target temporal",
      "/tmp/cleanup.sh"
    ]
    environment_vars = [
      "DEBIAN_FRONTEND=noninteractive"
    ]
  }

  # VirtualBox-only: repair netplan, regenerate SSH host keys, clean up and
  # zero the disk so the exported OVA is small. Not needed for hcloud snapshots.
  provisioner "shell" {
    only   = ["virtualbox-ovf.temporal"]
    inline = [
      "echo '=== Step 1: Repairing Empty Netplan Configuration ==='",
      "sudo mkdir -p /etc/netplan",
      
      # Using a clean bash heredoc to maintain YAML indentation structures
      <<-EOF
      sudo tee /etc/netplan/01-packer-fallback.yaml > /dev/null << 'NETPLAN'
      network:
        version: 2
        renderer: networkd
        ethernets:
          all-ethernet-cards:
            match:
              name: "en*"
            dhcp4: true
            dhcp6: true
      NETPLAN
      EOF
      ,

      "echo '=== Creating Automated SSH Key Regeneration Service ==='",
      
      # Using a standard bash heredoc to cleanly write the multi-line file
      <<-EOF
      sudo tee /etc/systemd/system/ssh-host-keygen.service > /dev/null << 'SERVICE'
      [Unit]
      Description=Regenerate SSH Host Keys if Missing
      Before=ssh.service sshd.service
      ConditionPathExistsGlob=!/etc/ssh/ssh_host_*_key

      [Service]
      Type=oneshot
      ExecStart=/usr/bin/ssh-keygen -A
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target
      SERVICE
      EOF
      ,

      # Secure file permissions and apply configuration
      "sudo chmod 644 /etc/systemd/system/ssh-host-keygen.service",
      "sudo systemctl daemon-reload",
      "sudo systemctl enable ssh-host-keygen.service",

      "sudo cp /home/packer/.ssh/authorized_keys /root/.ssh/authorized_keys",
      
      # Secure file permissions and apply configuration
      "sudo chmod 600 /etc/netplan/01-packer-fallback.yaml",
      "sudo netplan generate",

      "echo '=== Step 2: Cleaning up APT Caches and Logs ==='",
      "sudo apt-get autoremove --purge -y",
      "sudo apt-get clean",
      "sudo apt-get autoclean",
      "sudo journalctl --vacuum-time=1s",
      "sudo find /var/log -type f -exec truncate -s 0 {} \\;",
      "sudo rm -f /etc/udev/rules.d/70-persistent-net.rules",

      "echo '=== Step 3: Zeroing out drive to minimize final OVA size ==='",
      "sudo dd if=/dev/zero of=/zero.small.file bs=1M status=none || true",
      "sudo rm -f /zero.small.file",
      "sync"
    ]
  }

  # Clean up local verify binary
  provisioner "shell-local" {
    inline = [
      "rm -f ${path.root}/verify"
    ]
  }

  post-processor "manifest" {
    output     = "manifest.json"
    strip_path = true
    custom_data = {
      snapshot_name            = local.snapshot_name
      temporal_cli_version     = var.temporal_cli_version
      temporal_server_version  = var.temporal_server_version
      temporal_ui_version      = var.temporal_ui_version
      temporal_worker_version  = var.temporal_worker_version
      secret_operator_version  = var.secret_operator_version
      oauth2_storage_version   = var.oauth2_storage_version
      dunebot_version          = var.dunebot_version
    }
  }
}
