packer {
  required_plugins {
    hcloud = {
      source  = "github.com/hetznercloud/hcloud"
      version = ">= 1.3.0"
    }
  }
}

locals {
  timestamp = formatdate("YYYYMMDD-hhmmss", timestamp())
  snapshot_name = "${var.snapshot_name}-${local.timestamp}"
}

source "hcloud" "temporal" {
  image        = var.base_image
  location     = var.location
  server_type  = var.server_type
  server_name  = "packer-temporal-builder"
  ssh_username = "root"

  snapshot_name = local.snapshot_name
  snapshot_labels = {
    "app"                      = "temporal"
    "build_timestamp"          = local.timestamp
    "temporal_cli_version"     = var.temporal_cli_version
    "temporal_server_version"  = var.temporal_server_version
    "temporal_ui_version"      = var.temporal_ui_version
    "temporal_worker_version"  = var.temporal_worker_version
    "secret_operator_version"  = var.secret_operator_version
    "oauth2_storage_version"   = var.oauth2_storage_version
    "dunebot_version"          = var.dunebot_version
    "packer_build"             = "true"
  }
}

build {
  sources = ["source.hcloud.temporal"]

  # Build verify binary for target OS/architecture
  provisioner "shell-local" {
    inline = [
      "echo 'Building temporal-verify binary for ${var.target_goos}/${var.target_goarch}...'",
      "GOOS=${var.target_goos} GOARCH=${var.target_goarch} go build -o ${path.root}/temporal-verify ../../../cmd/verify/"
    ]
  }

  # Generate versions.env file from template
  provisioner "file" {
    content = templatefile("${path.root}/scripts/versions.env.tpl", {
      temporal_cli_version     = var.temporal_cli_version
      temporal_server_version  = var.temporal_server_version
      temporal_ui_version      = var.temporal_ui_version
      temporal_worker_version  = var.temporal_worker_version
      secret_operator_version  = var.secret_operator_version
      oauth2_storage_version   = var.oauth2_storage_version
      dunebot_version          = var.dunebot_version
    })
    destination = "/tmp/versions.env"
  }

  # Upload all provisioner scripts
  provisioner "file" {
    source      = "${path.root}/scripts/"
    destination = "/tmp/"
  }

  # Upload verify binary to permanent location (generated by shell-local provisioner above)
  provisioner "file" {
    source      = "${path.root}/temporal-verify"
    destination = "/usr/local/bin/temporal-verify"
    generated   = true
  }

  # Make scripts executable and run them in order
  provisioner "shell" {
    inline = [
      "chmod +x /tmp/*.sh /usr/local/bin/temporal-verify",
      ". /tmp/versions.env && /tmp/01-base-packages.sh",
      ". /tmp/versions.env && /tmp/02-temporal-binaries.sh",
      ". /tmp/versions.env && /tmp/03-dunebot-binaries.sh",
      "/tmp/04-nginx-setup.sh",
      "/tmp/05-systemd-services.sh",
      "/tmp/06-security-hardening.sh",
      "/usr/local/bin/temporal-verify --local --prebaked",
      "/tmp/07-cleanup.sh"
    ]
    environment_vars = [
      "DEBIAN_FRONTEND=noninteractive"
    ]
  }

  # Clean up local verify binary
  provisioner "shell-local" {
    inline = [
      "rm -f ${path.root}/temporal-verify"
    ]
  }

  post-processor "manifest" {
    output     = "manifest.json"
    strip_path = true
    custom_data = {
      snapshot_name            = local.snapshot_name
      temporal_cli_version     = var.temporal_cli_version
      temporal_server_version  = var.temporal_server_version
      temporal_ui_version      = var.temporal_ui_version
      temporal_worker_version  = var.temporal_worker_version
      secret_operator_version  = var.secret_operator_version
      oauth2_storage_version   = var.oauth2_storage_version
      dunebot_version          = var.dunebot_version
    }
  }
}
